/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pinturasbd.Views;

import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pinturasbd.Controllers.PotesJpaController;
import pinturasbd.models.Potes;

/**
 *
 * @author Angel
 */
public class Agregar extends javax.swing.JDialog {

    /**
     * Creates new form Agregar
     */
     Potes pot = new Potes();
    PotesJpaController ctrPotes = new PotesJpaController();
    public Agregar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getTable();
        this.setLocationRelativeTo(null);
    }
    
    private void getTable(){
        String colums[] = { "ID", "Nombre", "Codigo", "cantidad", "color", "marca", "textura"};
        DefaultTableModel models = new DefaultTableModel(colums, 0);
        Object [] obj = new Object[7];
        List ls;
        
         try {
            ls = ctrPotes.findPotesEntities();
            for (int i = 0; i <ls.size(); i++) {
                pot = (Potes) ls.get(i);
                obj[0] = pot.getPotId();
                obj[1] = pot.getNombre();
                obj[2] = pot.getCodigo();
                obj[3] = pot.getCantidad();
                obj[4] = pot.getColor();
                obj[5] = pot.getMarca();
                obj[6] = pot.getTextura();
                
                models.addRow(obj);
            }
                this.TablePintu.setModel(models);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error!!" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fSGradientPanel1 = new LIB.FSGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePintu = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTextura = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnAgregar = new LIB.FSButtonMD();
        btnEliminar = new LIB.FSButtonMD();
        btnModificar = new LIB.FSButtonMD();
        btnVaciar = new LIB.FSButtonMD();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        fSGradientPanel1.setFSEndColor(new java.awt.Color(102, 102, 255));
        fSGradientPanel1.setFSGradientFocus(1700);
        fSGradientPanel1.setFSStartColor(new java.awt.Color(0, 0, 153));

        TablePintu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablePintu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePintuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablePintu);

        txtId.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtId.setForeground(new java.awt.Color(0, 0, 204));
        txtId.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtId.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID:");

        txtNombre.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 204));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRE:");

        txtCodigo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(0, 0, 204));
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CODIGO:");

        txtCantidad.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(0, 0, 204));
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CANTIDAD:");

        txtColor.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtColor.setForeground(new java.awt.Color(0, 0, 204));
        txtColor.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("COLOR:");

        txtMarca.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtMarca.setForeground(new java.awt.Color(0, 0, 204));
        txtMarca.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MARCA:");

        txtTextura.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtTextura.setForeground(new java.awt.Color(0, 0, 204));
        txtTextura.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TEXTURA:");

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnVaciar.setText("VACIAR");
        btnVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fSGradientPanel1Layout = new javax.swing.GroupLayout(fSGradientPanel1);
        fSGradientPanel1.setLayout(fSGradientPanel1Layout);
        fSGradientPanel1Layout.setHorizontalGroup(
            fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fSGradientPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fSGradientPanel1Layout.createSequentialGroup()
                        .addGroup(fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGroup(fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fSGradientPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(txtTextura, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                            .addGroup(fSGradientPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNombre)
                                    .addComponent(txtCodigo)
                                    .addComponent(txtCantidad)
                                    .addComponent(txtColor)
                                    .addComponent(txtId))))
                        .addGap(19, 19, 19))
                    .addGroup(fSGradientPanel1Layout.createSequentialGroup()
                        .addGroup(fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVaciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fSGradientPanel1Layout.setVerticalGroup(
            fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(fSGradientPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTextura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVaciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fSGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fSGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (!txtNombre.getText().equals("")
                && !txtCantidad.getText().equals("")
                && !txtCodigo.getText().equals("")
                && !txtColor.getText().equals("")
                && !txtMarca.getText().equals("")
                && !txtTextura.getText().equals("")){

            //Definir EntityManagerFactory
            EntityManagerFactory emf = new Persistence().createEntityManagerFactory("PinturasBDPU");
            //Definir la instancia del controlador
            PotesJpaController controller = new PotesJpaController(emf);

            //Obtener los valores de todos los campos
            String Nombre = txtNombre.getText();
            int Cantidad = Integer.parseInt(txtCantidad.getText());
            int codigo = Integer.parseInt( txtCodigo.getText());
            String Color = txtColor.getText();
            String marca = txtMarca.getText();
            String textura = txtTextura.getText();
            
           

            //Instanciar una universidad y darle todos los valores segun los obtenidos arriba
            Potes pot = new Potes();
            pot.setNombre(Nombre);
            pot.setCantidad(Cantidad);
            pot.setCodigo(codigo);
            pot.setColor(Color);
            pot.setMarca(marca);
            pot.setTextura(textura);
            //Definir un try catch
            try {
                //Accedemos al metodo crear del controlador y le pasamos la universidad creada arriba
                controller.create(pot);
                getTable();
                //Si sale bien mostramos
                JOptionPane.showMessageDialog(null, " SU PRODUCTO FUE AGREGADO ");
            } catch (Exception e) {
                //Si sale mal mostramos
                JOptionPane.showMessageDialog(null, "Hubo error, intentelo nuevamente");
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
         if (!txtNombre.getText().equals("")
                && !txtCantidad.getText().equals("")
                && !txtCodigo.getText().equals("")
                && !txtColor.getText().equals("")
                && !txtMarca.getText().equals("")
                && !txtTextura.getText().equals("")){

            //Definir EntityManagerFactory
            EntityManagerFactory emf = new Persistence().createEntityManagerFactory("PinturasBDPU");
            //Definir la instancia del controlador
            PotesJpaController controller = new PotesJpaController(emf);

            //Obtener los valores de todos los campos
            String Nombre = txtNombre.getText();
            int Cantidad = Integer.parseInt(txtCantidad.getText());
            int codigo = Integer.parseInt( txtCodigo.getText());
            String Color = txtColor.getText();
            String marca = txtMarca.getText();
            String textura = txtTextura.getText();
            
           

            //Instanciar una universidad y darle todos los valores segun los obtenidos arriba
            Potes pot = new Potes();
            pot.setNombre(Nombre);
            pot.setCantidad(Cantidad);
            pot.setCodigo(codigo);
            pot.setColor(Color);
            pot.setMarca(marca);
            pot.setTextura(textura);
            //Definir un try catch
            try {
                //Accedemos al metodo crear del controlador y le pasamos la universidad creada arriba
                controller.edit(pot);
                getTable();
                //Si sale bien mostramos
                JOptionPane.showMessageDialog(null, " Su producto fue modificado ");
            } catch (Exception e) {
                //Si sale mal mostramos
                JOptionPane.showMessageDialog(null, "Hubo error, intentelo nuevamente");
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       EntityManagerFactory emf = new Persistence().createEntityManagerFactory("PinturasBDPU");
            PotesJpaController controller = new PotesJpaController(emf);

            Integer id = Integer.parseInt(txtId.getText());
            try {
                controller.destroy(id);
                JOptionPane.showMessageDialog(null, "Producto Eliminado ");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Hubo un error, intente nuevamente");
            }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void TablePintuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePintuMouseClicked
        this.txtId.setText(this.TablePintu.getValueAt(this.TablePintu.getSelectedRow(),0).toString());
        this.txtNombre.setText(this.TablePintu.getValueAt(this.TablePintu.getSelectedRow(),1).toString());
        this.txtCodigo.setText(this.TablePintu.getValueAt(this.TablePintu.getSelectedRow(),2).toString());
        this.txtCantidad.setText(this.TablePintu.getValueAt(this.TablePintu.getSelectedRow(),3).toString());
        this.txtColor.setText(this.TablePintu.getValueAt(this.TablePintu.getSelectedRow(),4).toString());
        this.txtMarca.setText(this.TablePintu.getValueAt(this.TablePintu.getSelectedRow(),5).toString());
        this.txtTextura.setText(this.TablePintu.getValueAt(this.TablePintu.getSelectedRow(),6).toString());
    }//GEN-LAST:event_TablePintuMouseClicked

    private void btnVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarActionPerformed
        txtId.setText("");
        txtNombre.setText("");
        txtCodigo.setText("");
        txtCantidad.setText("");
        txtColor.setText("");
        txtMarca.setText("");
        txtTextura.setText("");
    }//GEN-LAST:event_btnVaciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Agregar dialog = new Agregar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablePintu;
    private LIB.FSButtonMD btnAgregar;
    private LIB.FSButtonMD btnEliminar;
    private LIB.FSButtonMD btnModificar;
    private LIB.FSButtonMD btnVaciar;
    private LIB.FSGradientPanel fSGradientPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTextura;
    // End of variables declaration//GEN-END:variables
}
